name: CutsceneMaker
author: toxicity
description: making Cutscene
main: kor.toxicity.cutscenemaker.CutsceneMaker
version: 1.0
api-version: 1.13
softdepend:
  - EffectLib
  - Skript
  - WorldGuard
  - Vault
  - MythicMobs
  - LibsDisguises
  - Quest
depend:
  - ProtocolLib
commands:
  cutscene:
    description: Cutscene command
    usage: /<command>
    aliases: [cut,컷씬]
  quest:
      description: Cutscene quest
      usage: /<command>
      aliases: [q,퀘스트,퀘]